# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Staging

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
      - run: npm i -g @quasar/cli@latest
      - run: npm ci

      - name: Create public env file
        run: |
          cat << EOF >> .env.production.local
          ${{ secrets.ENV_FILE_STAGING }}
          EOF

      # - # Fill firebaseServiceAccountKey.json with an empty object
      #   name: Create firebaseServiceAccountKey.json
      #   run: |
      #     echo "{}" > firebaseServiceAccountKey.json

      - run: quasar build -m ssr -d --if-present

      - # Login against GitHub Container Registry
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - # Build and push Docker image
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/harmlesskey/harmlesskey_staging
